name: live_leaderboard_flutter
description: "A LeaderBoard Coding Challenge"
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  icons_launcher:
    image_path: "assets/icon.png"
    platforms:
      android:
        enable: true
      ios:
        enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

 
flutter:

 
  uses-material-design: true
 